TILE_INSIDE_WIDTH = 240
TILE_INSIDE_HEIGHT = 249
TILE_MARGIN = 8
TILE_WIDTH = TILE_INSIDE_WIDTH + TILE_MARGIN * 2
TILE_HEIGHT = TILE_INSIDE_HEIGHT + TILE_MARGIN * 2

TILE_GAP = 30 - TILE_MARGIN * 2

THUMB_WIDTH = 240
THUMB_HEIGHT = 135
